// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_QDc_IfGrypLSxrMnZnB773vXv_Bqbpc',
    appId: '1:230079462581:web:c832f38348cff017c312fc',
    messagingSenderId: '230079462581',
    projectId: 'social-app-adc99',
    authDomain: 'social-app-adc99.firebaseapp.com',
    storageBucket: 'social-app-adc99.appspot.com',
    measurementId: 'G-WYCQT1RC8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdInbLJ_YG_8dq6FPBhIszvt5lLjfUOoY',
    appId: '1:230079462581:android:3aa7fd02c290a45cc312fc',
    messagingSenderId: '230079462581',
    projectId: 'social-app-adc99',
    storageBucket: 'social-app-adc99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFtrADZZPI4ehPg80HpBEKbuJtLV5YMh4',
    appId: '1:230079462581:ios:8f6332bec6426b7dc312fc',
    messagingSenderId: '230079462581',
    projectId: 'social-app-adc99',
    storageBucket: 'social-app-adc99.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFtrADZZPI4ehPg80HpBEKbuJtLV5YMh4',
    appId: '1:230079462581:ios:1dc8076e9ff0b524c312fc',
    messagingSenderId: '230079462581',
    projectId: 'social-app-adc99',
    storageBucket: 'social-app-adc99.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
